### ISSUE TITLE
大佬，有没有考虑用Swift Macro实现呢

### ISSUE THREAD

**Issue by songgeb** [ExCodable/ExCodable#11]
感觉理论可行

**Comment by iwill** [comment]
找空研究一下 👌🏿

**Comment by songgeb** [comment]
> 找空研究一下 👌🏿

https://github.com/winddpan/CodableWrapper/tree/1.0.1
这哥们已经实现了

**Comment by iwill** [comment]
> > 找空研究一下 👌🏿
> 
> https://github.com/winddpan/CodableWrapper/tree/1.0.1 这哥们已经实现了

简单看了下 Swift Macros，貌似确实适合干这个，比之前的 `propertyWrapper` + `Mirror` 方案要好 👍🏿

**Comment by iwill** [comment]
刚刚又发现了这个 [MetaCodable](https://github.com/SwiftyLab/MetaCodable)，我好像可以省省了，哈哈

**Comment by songgeb** [comment]
👍🏻发自我的 iPhone在 2023年11月23日，13:11，Míng ***@***.***> 写道：﻿
刚刚又发现了这个 MetaCodable，我好像可以省省了，哈哈

**Comment by White8818** [comment]
> 刚刚又发现了这个 [MetaCodable](https://github.com/SwiftyLab/MetaCodable)，我好像可以省省了，哈哈

这个库，我研究用了下，默认值的写法不如你这个库方便，其他大差不差，可能也就是你这边用到了Mirror是个隐患（不是），不过我觉得应该问题不大，还是期待你更新一个版本的

**Comment by iwill** [comment]
> > 刚刚又发现了这个 [MetaCodable](https://github.com/SwiftyLab/MetaCodable)，我好像可以省省了，哈哈
> 
> 这个库，我研究用了下，默认值的写法不如你这个库方便，其他大差不差，可能也就是你这边用到了Mirror是个隐患（不是），不过我觉得应该问题不大，还是期待你更新一个版本的

感谢支持！我争取近期就发 1.0 🤣

`Mirror` 我前几天测试过，性能要比之前的手写 mapping 方案慢了一丢丢，但基本可以忽略 —— 只有苹果不故意搞它 ...
