### ISSUE TITLE
接口返回的response 映射问题

### ISSUE THREAD

**Issue by yonfong** [ExCodable/ExCodable#2]
请教下，后面接口返回的 外层json一般是通用字端  code、message、data，code 和 message是固定类型，而data 根据不同接口 返回的， 可能是 各种类型 或者 空值 我定义为Any？Xcode报Protocol 'Any' as a type cannot conform to 'Decodable'，这种情况时 最外层的 模型 想要用该库 进行定义并映射，该如何定义映射？如果前面的解决了，到具体接口返回的业务层 再根据情况 把data映射为 指定类型的模型，此时前面定义的 data 映射到指定类型模型是否有特别要注意的点？

**Comment by iwill** [comment]
这样可以吗，`ResponseWrapper` 用于解析统一的数据格式，泛型 `T` 用来解析 `data` 字段返回的不同格式的数据：
```swift
struct ResponseWrapper<T: Codable>: ExCodable {
    let code: Int?
    let message: String?
    let data: T?
}
```

**Comment by xuantong0815** [comment]
> 这样可以吗，`ResponseWrapper` 用于解析统一的数据格式，泛型 `T` 用来解析 `data` 字段返回的不同格式的数据：
> 
> ```swift
> struct ResponseWrapper<T: Codable>: ExCodable {
>     let code: Int?
>     let message: String?
>     let data: T?
> }
> ```

您好，这的话 keyMapping 应该要怎么取设置，麻烦指导下，万分感谢！！！

**Comment by iwill** [comment]
这里 `ResponseWrapper` 可以看做一个普通的 Model，泛型 `T` 是这个 Model 的一个属性的类型，`keyMapping` 的设置没有什么特别之处。

```swift
public struct ResponseWrapper<T: Codable> {
    public private(set) var code: Int = ResponseCode.error
    public var isSuccess: Bool { code == ResponseCode.success }
    public private(set) var message: String? = nil
    public private(set) var data: T? = nil
    public private(set) var timestamp: TimeInterval = 0.0
}

extension ResponseWrapper: ExCodable {
    public static var keyMapping: [KeyMap<Self>] {[
        KeyMap(\.code,      to: "code"),
        KeyMap(\.message,   to: "msg"),
        KeyMap(\.data,      to: "data"),
        KeyMap(\.timestamp, to: "ts")
    ]}
    public init(from decoder: Decoder) throws {
        try decode(from: decoder, with: Self.keyMapping)
    }
    public func encode(to encoder: Encoder) throws {
        try encode(to: encoder, with: Self.keyMapping)
    }
}

```
