### ISSUE TITLE
非值类型，其他类型的可以映射转换么？

### ISSUE THREAD

**Issue by HansRove** [ExCodable/ExCodable#4]
這庫很棒！~

// JSON:
{
"uid":888888,
"obj": {
"test1": "xxxx",
"test2": "xxxx"
}
}

某天变成：
// JSON:
{
"uid":888888,
"obj": []
}

后端PHP， 请问这样母模型还能转换出来么？ 如何定义model

**Comment by iwill** [comment]
`obj` 的类型变了多半是解析不出来的，除非 `obj` 是用通用类型解析，比如 [`JSON`](https://github.com/zoul/generic-json-swift)，然后程序动态地判断数据的具体类型、再走不同的解析逻辑。

**Comment by iwill** [comment]
@HansRove 刚发布了 1.0，支持灵活的自定义类型转换，应该可以解决你的问题。
