### ISSUE TITLE
请问还会更新吗？

### ISSUE THREAD

**Issue by White8818** [ExCodable/ExCodable#8]
你好，我最近也是刚转入swift，一直对于swift没有好的json转model库而苦恼，无意间看到作者的这个开源库，觉得很好用，但是我看develop分支领先于主分支代码，而且也好久没更新了。
请问还会更新吗？

**Comment by iwill** [comment]
你好，感谢好评！最近正打算更新一下呢。develop 分支用了 `Mirror`，担心性能有问题，还没做过测试，近期找时间测试一下，没问题就合并到 master。

**Comment by White8818** [comment]
收到！期待持续更新！感谢开源~
