### ISSUE TITLE
现在还是只能每个属性写全吗，之前的fb605c4好像没有了

### ISSUE THREAD

**Issue by songxing10000** [ExCodable/ExCodable#9]
之前一直用fb605c4自动处理每个属性，现在这个fb605c4被删除了，后续使用是不是只能每个属性写全啊， 或者有没有什么工具能自动写全的啊。之前的fb605c4自动处理每个属性的版本的代码是有性能问题吗

**Comment by iwill** [comment]
可以先使用 develop 分支，准备近期把它合并到 master，然后发布 1.0。

**Comment by songxing10000** [comment]
> 可以先使用 develop 分支，准备近期把它合并到 master，然后发布 1.0。

非常期待
